name: CI

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
  

  workflow_dispatch:

jobs:
  lint:
    runs-on: windows-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Run Lint
        run: ./gradlew lintDebug

      - name: Upload html test report
        uses: actions/upload-artifact@v2
        with:
          name: index.html
          path: app/build/reports/lint-results-debug.html

#  build:
#    runs-on: windows-latest
#
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Run a one-line script
#        run: echo Hello, world!
#
#      - name: Run a multi-line script
#        run: |
#          echo Add other actions to build,
#          echo test, and deploy your project.
#
#
#
